//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHK
    {
        public string MaCTHK { get; set; }
        public string MaHocSinh { get; set; }
        public string MaNamHoc { get; set; }
        public string MaHocKy { get; set; }
        public string MaHanhKiem { get; set; }
    
        public virtual HANHKIEM HANHKIEM { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
