//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTLOP
    {
        public string MaCTL { get; set; }
        public string MaHocSinh { get; set; }
        public string MaLop { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
