//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA_MONHOC_HOCSINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KETQUA_MONHOC_HOCSINH()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public string MaKetQua { get; set; }
        public string MaHocSinh { get; set; }
        public string MaNamHoc { get; set; }
        public string MaHocKy { get; set; }
        public string MaMonHoc { get; set; }
        public Nullable<double> DiemTB { get; set; }
        public string MaXepLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual HOCKY HOCKY { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
        public virtual XEPLOAI XEPLOAI { get; set; }
    }
}
