//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.CTLOPs = new HashSet<CTLOP>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string MaKhoi { get; set; }
        public Nullable<byte> SiSo { get; set; }
        public string MaNamHoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTLOP> CTLOPs { get; set; }
        public virtual KHOI KHOI { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
