//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string MaThamSo { get; set; }
        public Nullable<byte> TuoiToiThieu { get; set; }
        public Nullable<byte> TuoiToiDa { get; set; }
        public Nullable<short> SiSoToiDa { get; set; }
        public Nullable<double> DiemToiDa { get; set; }
        public Nullable<double> DiemToiThieu { get; set; }
    }
}
