//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinh
{
    using System;
    
    public partial class XepLoai_NamApDung_Result1
    {
        public string MaXepLoai { get; set; }
        public string TenXepLoai { get; set; }
        public Nullable<double> DiemToiThieu { get; set; }
        public Nullable<double> DiemToiDa { get; set; }
        public Nullable<double> DiemKhongChe { get; set; }
        public string NamApDung { get; set; }
    }
}
